### ISSUE TITLE
[QUESTION] - Delete anonymous post

### ISSUE THREAD

**Issue by AdrianTabacaru** [blueprintue/roadmap#56]
## Question
> Hello, I have added an anonymous post that I would like to delete.
Is there a way to do that?
Thank you!

**Comment by rancoud** [comment]
Hello,

Can you give me the url and I will remove it.

**Comment by AdrianTabacaru** [comment]
Great! Thank you so much!
https://blueprintue.com/blueprint/px00o5g4/

**Comment by rancoud** [comment]
The blueprint is now deleted :)

**Comment by AdrianTabacaru** [comment]
Thank you sir!
Cheers!
