### ISSUE TITLE
[FEATURE] - Plugin for Unreal Engine

### ISSUE THREAD

**Issue by rancoud** [blueprintue/roadmap#7]
## My suggestion
I would like to have a plugin for Unreal Engine

## Intended outcome
In Unreal Engine inside a blueprint Editor I would like to select nodes and paste them as anonymous blueprint on blueprintUE.

**Comment by Ecnassianer** [comment]
I searched for "BlueprintUE" on the marketplace, but couldn't find anything. Where can I find this plugin?

**Comment by rancoud** [comment]
@Ecnassianer 
The plugin is available here: https://github.com/blueprintue/blueprintue-cpp-plugin
It will be on the marketplace when the search and vault parts will be done.
